# Generated by Django 5.0.1 on 2024-01-18 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('nacimiento', models.DateField(blank=True, null=True)),
                ('vacunacion', models.BooleanField(blank=True)),
                ('desparasitado', models.BooleanField(blank=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gato',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='animales.animal')),
                ('color_pelo', models.CharField(max_length=30, null=True)),
                ('color_ojos', models.CharField(max_length=30, null=True)),
            ],
            bases=('animales.animal',),
        ),
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='animales.animal')),
                ('raza', models.CharField(max_length=50, null=True)),
            ],
            bases=('animales.animal',),
        ),
    ]
