# Generated by Django 5.0.1 on 2024-01-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0002_perro_tamano'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='castrado',
            field=models.BooleanField(blank=True, default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='contacto',
            field=models.CharField(default=351641514, max_length=30),
            preserve_default=False,
        ),
    ]
